import { IMovie } from "./movie"

export const MOVIES: IMovie[] = [
    {
        id: 1,
        title: "Only the brave",
        description: "Only the Brave is a 2017 American biographical drama film directed by Joseph Kosinski, and written by Ken Nolan and Eric Warren Singer, based on the GQ article No Exit by Sean Flynn.[1] The film tells the story of the Granite Mountain Hotshots, an elite crew of firefighters from Prescott, Arizona who lost 19 of 20 members while fighting the Yarnell Hill Fire in June 2013, and is dedicated to their memory. Only the Brave is a 2017 American biographical drama film directed by Joseph Kosinski, and written by Ken Nolan and Eric Warren Singer, based on the GQ article No Exit by Sean Flynn.[1] The film tells the story of the Granite Mountain Hotshots, an elite crew of firefighters from Prescott, Arizona who lost 19 of 20 members while fighting the Yarnell Hill Fire in June 2013, and is dedicated to their memory. It features an ensemble cast, including Josh Brolin, James Badge Dale, Jeff Bridges, Miles Teller, Alex Russell, Taylor Kitsch, Ben Hardy, Thad Luckinbill, Geoff Stults, Scott Haze, Andie MacDowell, and Jennifer Connelly.",
        year: 2017,
        imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRFH8v6RphwkKphoMVgdL8IUwOIs4jqKGEma3-iXFI2m7BovqTm",
        duration: { hours: 2, minutes: 13 },
        // genres: ["Action, Drama"],
    },
    {
        id: 2,
        title: "Man on Fire",
        description: "John, an ex-CIA officer, is entrusted with the responsibility of safeguarding an entrepreneur's daughter. When the girl gets kidnapped, John vows to seek revenge. Man on Fire is a 2004 action thriller film[4] directed by Tony Scott from a screenplay by Brian Helgeland, and based on the 1980 novel of the same name by A. J. Quinnell. The novel had previously been adapted into a feature film in 1987. In this film, Denzel Washington portrays John Creasy, a despondent, alcoholic former CIA SAD/SOG officer (and U.S. Marine Corps Force Reconnaissance captain) turned bodyguard, who goes on a revenge rampage after his charge, nine-year-old Lupita Pita Ramos (Dakota Fanning), is abducted in Mexico City. The supporting cast includes Christopher Walken, Radha Mitchell, Giancarlo Giannini, Marc Anthony, Rachel Ticotin and Mickey Rourke.",
        year: 2004,
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbhc2z7S5Xnu6pTZfza-mHcKhY4ieRX4s4ZuYmOLy0RCSBhvnX",
        duration: { hours: 2, minutes: 26 },
        // genres: ["Action, Drama"],
    },
    {
        id: 3,
        title: "Black Hawk Down",
        description: "Captain Mike Steele leads a team of nearly 100 US Army Rangers who travel to the capital city of Mogadishu to catch the top two lieutenants of a Somali warlord.. Black Hawk Down is a 2001 war film directed and produced by Ridley Scott, and co-produced by Jerry Bruckheimer, from a screenplay by Ken Nolan. It is based on the 1999 eponymous non-fiction by journalist Mark Bowden, about the crew of a Black Hawk helicopter that was shot down during the Battle of Mogadishu. The film features a large ensemble cast, including Josh Hartnett, Ewan McGregor, Eric Bana, Tom Sizemore, William Fichtner, Jason Isaacs, Sam Shepard, Jeremy Piven, Ioan Gruffudd, Ewen Bremner, Hugh Dancy, and Tom Hardy in his first film role. Orlando Bloom, Ty Burrell, and Nikolaj Coster-Waldau also have minor roles.",
        year: 2001,
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQrLPwoTp6Mmpik6F2FXYR_CtE2_7ZBsulsmh63xKW1tw_TqGDE",
        duration: { hours: 2, minutes: 24 },
        // genres: ["War, Drama"],
    },
    {
        id: 4,
        title: "Air",
        description: "Sonny Vaccaro and Nike pursue basketball rookie Michael Jordan, creating a partnership that revolutionizes the world of sports and contemporary culture. Air is a 2023 American biographical sports drama film directed by Ben Affleck and written by Alex Convery. The film is based on true events about the origin of Air Jordan, a basketball shoeline, of which a Nike employee seeks to strike a business deal with rookie player Michael Jordan. It stars Matt Damon, Ben Affleck, Jason Bateman, Marlon Wayans, Chris Messina, Chris Tucker and Viola Davis.",
        year: 2023,
        imageUrl: "https://themoviespoiler.com/wp-content/uploads/2023/04/air_ver12.jpg",
        duration: { hours: 1, minutes: 52 },
        // genres: ["Sport, Drama"],
    },
    {
        id: 5,
        title: "Dark Waters",
        description: "A tenacious attorney uncovers a dark secret that connects a growing number of unexplained deaths to one of the world's largest corporations. While trying to expose the truth, he soon finds himself risking his future, his family and his own life. Dark Waters is a 2019 American legal thriller film directed by Todd Haynes and written by Mario Correa and Matthew Michael Carnahan. The story dramatizes Robert Bilott's case against the chemical manufacturing corporation DuPont after they contaminated a town with unregulated chemicals. It stars Mark Ruffalo as Bilott, along with Anne Hathaway, Tim Robbins, Bill Camp, Victor Garber, Mare Winningham, William Jackson Harper, and Bill Pullman.",
        year: 2019,
        imageUrl: "https://m.media-amazon.com/images/M/MV5BODQ0M2Y5M2QtZGIwMC00MzJjLThlMzYtNmE3ZTMzZTYzOGEwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        duration: { hours: 2, minutes: 6 },
        // genres: ["Thriller, Drama"],
    },
    {
        id: 6,
        title: "Ford v Ferrari",
        description: "Carroll Shelby, an automotive designer, and Ken Miles, a race car driver, join hands to build a trailblazing vehicle and compete against the Ferrari race cars. Ford v Ferrari (titled Le Mans '66 in some European countries)[4] is a 2019 American biographical sports drama film directed by James Mangold and written by Jez Butterworth, John-Henry Butterworth, and Jason Keller. It stars Matt Damon and Christian Bale, with Jon Bernthal, Caitríona Balfe, Tracy Letts, Josh Lucas, Noah Jupe, Remo Girone, and Ray McKinnon in supporting roles. The plot follows a determined team of American and Swedish engineers and designers, led by automotive designer Carroll Shelby and his British driver, Ken Miles, who are hired by Henry Ford II and Lee Iacocca to build a race car to defeat the perennially dominant Italian racing team Scuderia Ferrari at the 1966 24 Hours of Le Mans race in France.",
        year: 2019,
        imageUrl: "https://m.media-amazon.com/images/M/MV5BM2UwMDVmMDItM2I2Yi00NGZmLTk4ZTUtY2JjNTQ3OGQ5ZjM2XkEyXkFqcGdeQXVyMTA1OTYzOTUx._V1_.jpg",
        duration: { hours: 2, minutes: 32 },
        // genres: ["Sport, Drama"],
    },
    {
        id: 7,
        title: "I Can Only Imagine",
        description: "Growing up in Greenville, Texas, Bart Millard suffers physical and emotional abuse at the hands of his father, Arthur. When Arthur becomes terminally ill, he finds redemption by embracing his faith and rediscovering his love for his son. Years later, Bart's troubled childhood and mended relationship with his dad inspires him to write the hit song I Can Only Imagine as singer of the Christian band MercyMe.I Can Only Imagine is a 2018 American Christian biographical drama film directed by the Erwin Brothers and written by Alex Cramer, Jon Erwin, and Brent McCorkle, based on the story behind the group MercyMe's song of the same name, the best-selling Christian single of all time.[4] The film stars J. Michael Finley as Bart Millard, the lead singer who wrote the song about his relationship with his father (Dennis Quaid). Madeline Carroll, Trace Adkins, Priscilla Shirer, and Cloris Leachman also star.",
        year: 2018,
        imageUrl: "https://i1.netflixmovies.com/dibsl9ebc/image/upload/w_600,h_891,c_lfill,g_north/myysk4b3aymrr0axydx4.jpg",
        duration: { hours: 1, minutes: 50 },
        // genres: ["Musical, Drama"],
    },
    {
        id: 8,
        title: "Interstellar",
        description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans. nterstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine. Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind. ",
        year: 2014,
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRf61mker2o4KH3CbVE7Zw5B1-VogMH8LfZHEaq3UdCMLxARZAB",
        duration: { hours: 2, minutes: 49 },
        // genres: ["Sci-fi, Drama"],
    },
    {
        id: 9,
        title: "Richard Jewell",
        description: "Richard Jewell, a security guard, alerts the police about a possible bomb in Centennial Park and is hailed as a hero. However, he soon becomes a prime suspect for the bombing. Richard Jewell is a 2019 American biographical drama film directed and produced by Clint Eastwood and written by Billy Ray. It is based on the 1997 Vanity Fair article American Nightmare: The Ballad of Richard Jewell by Marie Brenner and the 2019 book The Suspect: An Olympic Bombing, the FBI, the Media, and Richard Jewell, the Man Caught in the Middle by Kent Alexander and Kevin Salwen.[5][6][7][8][9] The film depicts the July 27 Centennial Olympic Park bombing and its aftermath, as security guard Richard Jewell finds a bomb during the 1996 Summer Olympics in Atlanta, Georgia, and alerts authorities to evacuate, only to later be wrongly accused of having placed the device himself. The film stars Paul Walter Hauser as Jewell,[10] alongside Sam Rockwell, Kathy Bates, Jon Hamm, and Olivia Wilde.",
        year: 2019,
        imageUrl: "https://musicart.xboxlive.com/7/5c375100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080",
        duration: { hours: 2, minutes: 9 },
        // genres: ["Crime, Drama"],
    },
    {
        id: 10,
        title: "Serenity",
        description: "Baker Dill is a fishing boat captain who leads tours off of the tranquil enclave of Plymouth Island. His peaceful life is soon shattered when his ex-wife Karen tracks him down. Desperate for help, Karen begs Baker to save her -- and their young son -- from her abusive husband. She wants him to take the brute out for a fishing excursion -- then throw him overboard to the sharks. Thrust back into a life that he wanted to forget, Baker now finds himself struggling to choose between right and wrong. Serenity is a 2019 American mystery thriller film written, produced and directed by Steven Knight.[5] The film stars Matthew McConaughey, Anne Hathaway, Diane Lane, Jason Clarke, Djimon Hounsou, and Jeremy Strong, and follows a fishing boat captain who is approached by his ex-wife to murder her abusive new husband. First announced in January 2017, principal photography on the film began on Mauritius that July.",
        year: 2019,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrxm_lZM0yqzAWtaysLnqrWZPaLZTL9qWYmPAdNd5WX3ml5_v4",
        duration: { hours: 1, minutes: 46 },
        // genres: ["Mystery, Drama"],
    },
    {
        id: 11,
        title: "Sully: Miracle on the Hudson",
        description: "Captain Chesley, a commercial pilot, makes an emergency landing on the Hudson River after his plane gets hit by birds. However, an investigation into the matter might prove to be fatal to his career. Sully (also known as Sully: Miracle on the Hudson[6]) is a 2016 American biographical drama film directed by Clint Eastwood and written by Todd Komarnicki, based on the 2009 autobiography Highest Duty by Chesley Sully Sullenberger and Jeffrey Skiles. Tom Hanks stars as Sullenberger, with Aaron Eckhart, Laura Linney, Anna Gunn, Autumn Reeser, Holt McCallany, and Jamey Sheridan. The film follows Sullenberger's January 2009 emergency landing of US Airways Flight 1549 on the Hudson River, in which all 155 passengers and crew survived – most suffering only minor injuries – and the subsequent publicity and investigation.",
        year: 2016,
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS6x2sGBjZwUdxcWNkZn1ODfxZ4-7z-00Bk9qZRCQFN8C-0ssO6",
        duration: { hours: 1, minutes: 36 },
        // genres: ["Drama"],
    },
    {
        id: 12,
        title: "The Last Full Measure",
        description: "Thirty-four years after his death, irman William H. Pitsenbarger Jr. is awarded the Medal of Honor for his service and actions on the battlefield. The Last Full Measure is a 2019 American war drama film written and directed by Todd Robinson. It follows the efforts of fictional Pentagon staffer Scott Huffman and many veterans to see the Medal of Honor awarded to William H. Pitsenbarger, a United States Air Force Pararescueman who flew in helicopter rescue missions during the Vietnam War to aid downed soldiers and pilots.[3][4] Based on true events, the film stars Sebastian Stan, Christopher Plummer, William Hurt, Ed Harris, Samuel L. Jackson, Jeremy Irvine, and Peter Fonda. It was the final film appearance of Fonda, who died before the film’s release; and Plummer's final on screen appearance before his death in 2021, though it had filmed prior to Knives Out which was released before it.",
        year: 2019,
        imageUrl: "https://www.movies.ie/wp-content/uploads/2019/11/TheLastFullMeasureposter.jpg",
        duration: { hours: 1, minutes: 50 },
        // genres: ["War , Drama"],
    }
]